### PR TITLE
Update to angular 16

### LINKED ISSUE #391: Angular 16 Compatibility - Error
I would like to know what estimated date you have to launch the version compatible with Angular 16
Thanks

### PR DESCRIPTION
**Pull request by leifjones**
Fix #391

### CODE REVIEW

**Comment by bdwellons** [comment]
Would love to see this merged.

**Comment by leifjones** [comment]
It may not be ready because the tests are failing. Though, to be honest, I'm not sure if it should be a blocker. (I didn't check if they were passing on the main branch yet.)

Also, to be honest, I am not planning to put more into this PR. Anyone is free to fork, replicate, or replace this.

**Comment by bdwellons** [comment]
I found a thread that recommended a new wrapper for highcharts on NPM called highcharts-angular. Worked great with Angular 16.x last night.

**Comment by leifjones** [comment]
Closing in deference to #393

**Pull request closed without merging**
