### PR TITLE
Update to Angular 15

### LINKED ISSUE #386: Angular 15 incompatibility
Could this be upgraded to Angular 15 compatibility?

https://update.angular.io/?l=3&v=14.0-15.0

### PR DESCRIPTION
**Pull request by leifjones**
Fix #386

### CODE REVIEW

**Comment by mrsegen** [comment]
@cebor Hello! I offer this update for your consideration. I'm trying to update our app to Angular 15, but this is a barrier to RenovateBot being able to create PRs successfully (because `npm install --force` is currently required as a workaroun)

**Review by prasath-sivalingam — APPROVED** [review]

**Comment by cebor** [comment]
we also need a new tag, will ad this after some checks

**Review by OleksandrBohuslavskyi — CHANGES_REQUESTED** [review]
Please, update eslint up to [v15.2.0](https://github.com/angular-eslint/angular-eslint/releases/tag/v15.2.0)

**Comment by leifjones** [comment]
@OleksandrBohuslavskyi The PR is open for maintainers to make changes. Feel free to make the change if you get to it before

**Comment by cebor** [comment]
Hi, thanks for your work, squashed your changes into following commit: https://github.com/cebor/angular-highcharts/commit/e27482aaf7eb305e0258a8561b058e962ce0a015

Also bumped to new version and pushed a release to npm.

**Pull request closed without merging**
