### PR TITLE
Improved Chart and StockChart classes with better type assertions

### PR DESCRIPTION
**Pull request by timperez-weather**
This PR should make a lot of people happy by providing better type assertions along with some improved logic around member property checking. The largest benefit is that developers will better be able to see auto-completion / type hinting on any properties, nested properties and method arguments within their IDE.

Best Regards,
**Timothy A. Perez**
App Architect / Senior Developer
The Weather Company, an IBM Business
tim.perez@weather.com
timothy.a.perez@ibm.com

**IBM** Watson

### CODE REVIEW

**Comment by timperez-weather** [comment]
@cebor The type definition file (highstock.d.ts) is in "@types/highcharts" node module by default. I think the changes in my last commit should be adequate. As far as in exterior projects utilizing angular-highcharts, I noticed Highstock does become global the moment you add it to the modules array in the highchartsModule factory. If I missed anything else, feel free to modify it or point out specifics for me to fix. Thanks for considering these changes.

**Comment by cebor** [comment]
@timperez-weather Ok i need some time for testing these changes, after that i will merge it in.

**Comment by cebor** [comment]
@timperez-weather ok, code seems working, but there are many new warning while running `./build.sh`.

Please resolve all the warnings and i can merge this in.

**Comment by timperez-weather** [comment]
@cebor done.

**Comment by cebor** [comment]
Nice! Great work, thanks. Sorry hadn't enough time to merge this in earlier.

**Pull request merged**
